export class Stock{
    prod_list = 
    [
        {
            prod:
            {
                id:"",
                descrip:"Reglilla de Pino Rustica: 1 x 1 x 10",
                cost:"",
                rust_price:"8",
                cepi_price:"10",
                stock_list:
                [
                    {
                        suc_id:"001",
                        suc_name:"Central",
                        stock:"0"
                    }
                ]
            }
        },
        {
            prod:
            {
                id:"",
                descrip:"Reglilla de Pino Rustica: 1 x 2 x 7",
                cost:"",
                rust_price:"9",
                cepi_price:"12",
                stock_list:
                [
                    {
                        suc_id:"001",
                        suc_name:"Central",
                        stock:"0"
                    }
                ]
            }
        },
        {
            prod:
            {
                id:"",
                descrip:"Reglilla de Pino Rustica: 1 x 2 X 8",
                cost:"",
                rust_price:"10",
                cepi_price:"12",
                stock_list:
                [
                    {
                        suc_id:"001",
                        suc_name:"Central",
                        stock:"0"
                    }
                ]
            }
        },
        {
            prod:
            {
                id:"",
                descrip:"Reglilla de Pino Rustica: 1 x 2 X 9",
                cost:"",
                rust_price:"12",
                cepi_price:"15",
                stock_list:
                [
                    {
                        suc_id:"001",
                        suc_name:"Central",
                        stock:"0"
                    }
                ]
            }
        },
        {
            prod:
            {
                id:"",
                descrip:"Reglilla de Pino Rustica: 1 x 2 X 10",
                cost:"",
                rust_price:"15",
                cepi_price:"18",
                stock_list:
                [
                    {
                        suc_id:"001",
                        suc_name:"Central",
                        stock:"0"
                    }
                ]
            }
        },
        {
            prod:
            {
                id:"",
                descrip:"Reglilla de Pino Rustica: 1 x 2 X 12",
                cost:"",
                rust_price:"18",
                cepi_price:"23",
                stock_list:
                [
                    {
                        suc_id:"001",
                        suc_name:"Central",
                        stock:"0"
                    }
                ]
            }
        },
        {
            prod:
            {
                id:"",
                descrip:"Reglilla de Pino Rustica: 1 x 3 X 7",
                cost:"",
                rust_price:"15",
                cepi_price:"18",
                stock_list:
                [
                    {
                        suc_id:"001",
                        suc_name:"Central",
                        stock:"0"
                    }
                ]
            }
        },
        {
            prod:
            {
                id:"",
                descrip:"Reglilla de Pino Rustica: 1 x 3 X 8",
                cost:"",
                rust_price:"18",
                cepi_price:"20",
                stock_list:
                [
                    {
                        suc_id:"001",
                        suc_name:"Central",
                        stock:"0"
                    }
                ]
            }
        },
        {
            prod:
            {
                id:"",
                descrip:"Reglilla de Pino Rustica: 1 x 3 X 9",
                cost:"",
                rust_price:"20",
                cepi_price:"22",
                stock_list:
                [
                    {
                        suc_id:"001",
                        suc_name:"Central",
                        stock:"0"
                    }
                ]
            }
        },
        {
            prod:
            {
                id:"",
                descrip:"Reglilla de Pino Rustica: 1 x 3 X 10",
                cost:"",
                rust_price:"22",
                cepi_price:"25",
                stock_list:
                [
                    {
                        suc_id:"001",
                        suc_name:"Central",
                        stock:"0"
                    }
                ]
            }
        },
        {
            prod:
            {
                id:"",
                descrip:"Reglilla de Pino Rustica: 1 x 3 X 12",
                cost:"",
                rust_price:"25",
                cepi_price:"30",
                stock_list:
                [
                    {
                        suc_id:"001",
                        suc_name:"Central",
                        stock:"0"
                    }
                ]
            }
        },
        {
            prod:
            {
                id:"",
                descrip:"Reglilla de Pino Rustica: 1 x 4 X 7",
                cost:"",
                rust_price:"20",
                cepi_price:"23",
                stock_list:
                [
                    {
                        suc_id:"001",
                        suc_name:"Central",
                        stock:"0"
                    }
                ]
            }
        },
        {
            prod:
            {
                id:"",
                descrip:"Reglilla de Pino Rustica: 1 x 4 X 8",
                cost:"",
                rust_price:"24",
                cepi_price:"28",
                stock_list:
                [
                    {
                        suc_id:"001",
                        suc_name:"Central",
                        stock:"0"
                    }
                ]
            }
        },
        {
            prod:
            {
                id:"",
                descrip:"Reglilla de Pino Rustica: 1 x 4 X 9",
                cost:"",
                rust_price:"28",
                cepi_price:"30",
                stock_list:
                [
                    {
                        suc_id:"001",
                        suc_name:"Central",
                        stock:"0"
                    }
                ]
            }
        },
        {
            prod:
            {
                id:"",
                descrip:"Reglilla de Pino Rustica: 1 x 4 X 10",
                cost:"",
                rust_price:"30",
                cepi_price:"33",
                stock_list:
                [
                    {
                        suc_id:"001",
                        suc_name:"Central",
                        stock:"0"
                    }
                ]
            }
        },
        {
            prod:
            {
                id:"",
                descrip:"Reglilla de Pino Rustica: 1 x 4 X 12",
                cost:"",
                rust_price:"35",
                cepi_price:"40",
                stock_list:
                [
                    {
                        suc_id:"001",
                        suc_name:"Central",
                        stock:"0"
                    }
                ]
            }
        },
        {
            prod:
            {
                id:"",
                descrip:"Reglilla de Pino Rustica: 1 x 6 X 7",
                cost:"",
                rust_price:"33",
                cepi_price:"35",
                stock_list:
                [
                    {
                        suc_id:"001",
                        suc_name:"Central",
                        stock:"0"
                    }
                ]
            }
        },
        {
            prod:
            {
                id:"",
                descrip:"Reglilla de Pino Rustica: 1 x 6 X 8",
                cost:"",
                rust_price:"35",
                cepi_price:"38",
                stock_list:
                [
                    {
                        suc_id:"001",
                        suc_name:"Central",
                        stock:"0"
                    }
                ]
            }
        },
        {
            prod:
            {
                id:"",
                descrip:"Reglilla de Pino Rustica: 1 x 6 X 9",
                cost:"",
                rust_price:"38",
                cepi_price:"40",
                stock_list:
                [
                    {
                        suc_id:"001",
                        suc_name:"Central",
                        stock:"0"
                    }
                ]
            }
        },
        {
            prod:
            {
                id:"",
                descrip:"Reglilla de Pino Rustica: 1 x 6 X 10",
                cost:"",
                rust_price:"42",
                cepi_price:"45",
                stock_list:
                [
                    {
                        suc_id:"001",
                        suc_name:"Central",
                        stock:"0"
                    }
                ]
            }
        },
        {
            prod:
            {
                id:"",
                descrip:"Reglilla de Pino Rustica: 1 x 6 X 12",
                cost:"",
                rust_price:"50",
                cepi_price:"55",
                stock_list:
                [
                    {
                        suc_id:"001",
                        suc_name:"Central",
                        stock:"0"
                    }
                ]
            }
        },
        {
            prod:
            {
                id:"",
                descrip:"Reglilla de Pino Rustica: 1 x 8 X 9",
                cost:"",
                rust_price:"50",
                cepi_price:"55",
                stock_list:
                [
                    {
                        suc_id:"001",
                        suc_name:"Central",
                        stock:"0"
                    }
                ]
            }
        },
        {
            prod:
            {
                id:"",
                descrip:"Reglilla de Pino Rustica: 1 x 8 X 10",
                cost:"",
                rust_price:"58",
                cepi_price:"62",
                stock_list:
                [
                    {
                        suc_id:"001",
                        suc_name:"Central",
                        stock:"0"
                    }
                ]
            }
        },
        {
            prod:
            {
                id:"",
                descrip:"Reglilla de Pino Rustica: 1 x 8 X 12",
                cost:"",
                rust_price:"70",
                cepi_price:"75",
                stock_list:
                [
                    {
                        suc_id:"001",
                        suc_name:"Central",
                        stock:"0"
                    }
                ]
            }
        },
        {
            prod:
            {
                id:"",
                descrip:"Reglilla de Pino Rustica: 1 x 10 x 9",
                cost:"",
                rust_price:"65",
                cepi_price:"70",
                stock_list:
                [
                    {
                        suc_id:"001",
                        suc_name:"Central",
                        stock:"0"
                    }
                ]
            }
        },
        {
            prod:
            {
                id:"",
                descrip:"Reglilla de Pino Rustica: 1 x 10 x 10",
                cost:"",
                rust_price:"75",
                cepi_price:"80",
                stock_list:
                [
                    {
                        suc_id:"001",
                        suc_name:"Central",
                        stock:"0"
                    }
                ]
            }
        },
        {
            prod:
            {
                id:"",
                descrip:"Reglilla de Pino Rustica: 1 x 10 x 12",
                cost:"",
                rust_price:"90",
                cepi_price:"95",
                stock_list:
                [
                    {
                        suc_id:"001",
                        suc_name:"Central",
                        stock:"0"
                    }
                ]
            }
        },
        {
            prod:
            {
                id:"",
                descrip:"Reglilla de Pino Rustica: 1 x 12 x 7",
                cost:"",
                rust_price:"60",
                cepi_price:"65",
                stock_list:
                [
                    {
                        suc_id:"001",
                        suc_name:"Central",
                        stock:"0"
                    }
                ]
            }
        },
        {
            prod:
            {
                id:"",
                descrip:"Reglilla de Pino Rustica: 1 x 12 x 8",
                cost:"",
                rust_price:"68",
                cepi_price:"72",
                stock_list:
                [
                    {
                        suc_id:"001",
                        suc_name:"Central",
                        stock:"0"
                    }
                ]
            }
        },
        {
            prod:
            {
                id:"",
                descrip:"Reglilla de Pino Rustica: 1 x 12 x 9",
                cost:"",
                rust_price:"77",
                cepi_price:"80",
                stock_list:
                [
                    {
                        suc_id:"001",
                        suc_name:"Central",
                        stock:"0"
                    }
                ]
            }
        },
        {
            prod:
            {
                id:"",
                descrip:"Reglilla de Pino Rustica: 1 x 12 x 10",
                cost:"",
                rust_price:"90",
                cepi_price:"95",
                stock_list:
                [
                    {
                        suc_id:"001",
                        suc_name:"Central",
                        stock:"0"
                    }
                ]
            }
        },
        {
            prod:
            {
                id:"",
                descrip:"Reglilla de Pino Rustica: 1 x 12 x 12",
                cost:"",
                rust_price:"115",
                cepi_price:"120",
                stock_list:
                [
                    {
                        suc_id:"001",
                        suc_name:"Central",
                        stock:"0"
                    }
                ]
            }
        },
        {
            prod:
            {
                id:"",
                descrip:"Reglilla de Pino Rustica: 2 x 2 x 7",
                cost:"",
                rust_price:"18",
                cepi_price:"21",
                stock_list:
                [
                    {
                        suc_id:"001",
                        suc_name:"Central",
                        stock:"0"
                    }
                ]
            }
        },
        {
            prod:
            {
                id:"",
                descrip:"Reglilla de Pino Rustica: 2 x 2 x 8",
                cost:"",
                rust_price:"20",
                cepi_price:"23",
                stock_list:
                [
                    {
                        suc_id:"001",
                        suc_name:"Central",
                        stock:"0"
                    }
                ]
            }
        },
        {
            prod:
            {
                id:"",
                descrip:"Reglilla de Pino Rustica: 2 x 2 x 9",
                cost:"",
                rust_price:"23",
                cepi_price:"26",
                stock_list:
                [
                    {
                        suc_id:"001",
                        suc_name:"Central",
                        stock:"0"
                    }
                ]
            }
        },
        {
            prod:
            {
                id:"",
                descrip:"Reglilla de Pino Rustica: 2 x 2 x 10",
                cost:"",
                rust_price:"25",
                cepi_price:"30",
                stock_list:
                [
                    {
                        suc_id:"001",
                        suc_name:"Central",
                        stock:"0"
                    }
                ]
            }
        },
        {
            prod:
            {
                id:"",
                descrip:"Reglilla de Pino Rustica: 2 x 2 x 12",
                cost:"",
                rust_price:"30",
                cepi_price:"35",
                stock_list:
                [
                    {
                        suc_id:"001",
                        suc_name:"Central",
                        stock:"0"
                    }
                ]
            }
        },
        {
            prod:
            {
                id:"",
                descrip:"Reglilla de Pino Rustica: 2 x 3 x 7",
                cost:"",
                rust_price:"25",
                cepi_price:"30",
                stock_list:
                [
                    {
                        suc_id:"001",
                        suc_name:"Central",
                        stock:"0"
                    }
                ]
            }
        },
        {
            prod:
            {
                id:"",
                descrip:"Reglilla de Pino Rustica: 2 x 3 x 8",
                cost:"",
                rust_price:"30",
                cepi_price:"35",
                stock_list:
                [
                    {
                        suc_id:"001",
                        suc_name:"Central",
                        stock:"0"
                    }
                ]
            }
        },
        {
            prod:
            {
                id:"",
                descrip:"Reglilla de Pino Rustica: 2 x 3 x 9",
                cost:"",
                rust_price:"35",
                cepi_price:"40",
                stock_list:
                [
                    {
                        suc_id:"001",
                        suc_name:"Central",
                        stock:"0"
                    }
                ]
            }
        },
        {
            prod:
            {
                id:"",
                descrip:"Reglilla de Pino Rustica: 2 x 3 x 10",
                cost:"",
                rust_price:"40",
                cepi_price:"45",
                stock_list:
                [
                    {
                        suc_id:"001",
                        suc_name:"Central",
                        stock:"0"
                    }
                ]
            }
        },
        {
            prod:
            {
                id:"",
                descrip:"Reglilla de Pino Rustica: 2 x 3 x 12",
                cost:"",
                rust_price:"45",
                cepi_price:"50",
                stock_list:
                [
                    {
                        suc_id:"001",
                        suc_name:"Central",
                        stock:"0"
                    }
                ]
            }
        },
        {
            prod:
            {
                id:"",
                descrip:"Reglilla de Pino Rustica: 3 x 3 x 7",
                cost:"",
                rust_price:"40",
                cepi_price:"45",
                stock_list:
                [
                    {
                        suc_id:"001",
                        suc_name:"Central",
                        stock:"0"
                    }
                ]
            }
        },
        {
            prod:
            {
                id:"",
                descrip:"Reglilla de Pino Rustica: 3 x 3 x 8",
                cost:"",
                rust_price:"45",
                cepi_price:"50",
                stock_list:
                [
                    {
                        suc_id:"001",
                        suc_name:"Central",
                        stock:"0"
                    }
                ]
            }
        },
        {
            prod:
            {
                id:"",
                descrip:"Reglilla de Pino Rustica: 3 x 3 x 9",
                cost:"",
                rust_price:"50",
                cepi_price:"55",
                stock_list:
                [
                    {
                        suc_id:"001",
                        suc_name:"Central",
                        stock:"0"
                    }
                ]
            }
        },
        {
            prod:
            {
                id:"",
                descrip:"Reglilla de Pino Rustica: 3 x 3 x 10",
                cost:"",
                rust_price:"60",
                cepi_price:"65",
                stock_list:
                [
                    {
                        suc_id:"001",
                        suc_name:"Central",
                        stock:"0"
                    }
                ]
            }
        },
        {
            prod:
            {
                id:"",
                descrip:"Reglilla de Pino Rustica: 3 x 3 x 12",
                cost:"",
                rust_price:"70",
                cepi_price:"75",
                stock_list:
                [
                    {
                        suc_id:"001",
                        suc_name:"Central",
                        stock:"0"
                    }
                ]
            }
        },
        {
            prod:
            {
                id:"",
                descrip:"Reglilla de Pino Rustica: 3 x 4 x 7",
                cost:"",
                rust_price:"50",
                cepi_price:"55",
                stock_list:
                [
                    {
                        suc_id:"001",
                        suc_name:"Central",
                        stock:"0"
                    }
                ]
            }
        },
        {
            prod:
            {
                id:"",
                descrip:"Reglilla de Pino Rustica: 3 x 4 x 8",
                cost:"",
                rust_price:"60",
                cepi_price:"65",
                stock_list:
                [
                    {
                        suc_id:"001",
                        suc_name:"Central",
                        stock:"0"
                    }
                ]
            }
        },
        {
            prod:
            {
                id:"",
                descrip:"Reglilla de Pino Rustica: 3 x 4 x 9",
                cost:"",
                rust_price:"70",
                cepi_price:"75",
                stock_list:
                [
                    {
                        suc_id:"001",
                        suc_name:"Central",
                        stock:"0"
                    }
                ]
            }
        },
        {
            prod:
            {
                id:"",
                descrip:"Reglilla de Pino Rustica: 3 x 4 x 10",
                cost:"",
                rust_price:"75",
                cepi_price:"80",
                stock_list:
                [
                    {
                        suc_id:"001",
                        suc_name:"Central",
                        stock:"0"
                    }
                ]
            }
        },
        {
            prod:
            {
                id:"",
                descrip:"Reglilla de Pino Rustica: 3 x 4 x 12",
                cost:"",
                rust_price:"95",
                cepi_price:"100",
                stock_list:
                [
                    {
                        suc_id:"001",
                        suc_name:"Central",
                        stock:"0"
                    }
                ]
            }
        },
        {
            prod:
            {
                id:"",
                descrip:"Reglilla de Pino Rustica: 4 x 4 x 7",
                cost:"",
                rust_price:"70",
                cepi_price:"75",
                stock_list:
                [
                    {
                        suc_id:"001",
                        suc_name:"Central",
                        stock:"0"
                    }
                ]
            }
        },
        {
            prod:
            {
                id:"",
                descrip:"Reglilla de Pino Rustica: 4 x 4 x 8",
                cost:"",
                rust_price:"80",
                cepi_price:"85",
                stock_list:
                [
                    {
                        suc_id:"001",
                        suc_name:"Central",
                        stock:"0"
                    }
                ]
            }
        },
        {
            prod:
            {
                id:"",
                descrip:"Reglilla de Pino Rustica: 4 x 4 x 9",
                cost:"",
                rust_price:"90",
                cepi_price:"55",
                stock_list:
                [
                    {
                        suc_id:"001",
                        suc_name:"Central",
                        stock:"0"
                    }
                ]
            }
        },
        {
            prod:
            {
                id:"",
                descrip:"Reglilla de Pino Rustica: 4 x 4 x 10",
                cost:"",
                rust_price:"100",
                cepi_price:"110",
                stock_list:
                [
                    {
                        suc_id:"001",
                        suc_name:"Central",
                        stock:"0"
                    }
                ]
            }
        },
        {
            prod:
            {
                id:"",
                descrip:"Reglilla de Pino Rustica: 4 x 4 x 12",
                cost:"",
                rust_price:"135",
                cepi_price:"145",
                stock_list:
                [
                    {
                        suc_id:"001",
                        suc_name:"Central",
                        stock:"0"
                    }
                ]
            }
        },
        {
            prod:
            {
                id:"",
                descrip:"Regra de Pino Rustico: 5 x 5 x 7",
                cost:"",
                rust_price:"125",
                cepi_price:"135",
                stock_list:
                [
                    {
                        suc_id:"001",
                        suc_name:"Central",
                        stock:"0"
                    }
                ]
            }
        },
        {
            prod:
            {
                id:"",
                descrip:"Regra de Pino Rustico: 5 x 5 x 8",
                cost:"",
                rust_price:"140",
                cepi_price:"150",
                stock_list:
                [
                    {
                        suc_id:"001",
                        suc_name:"Central",
                        stock:"0"
                    }
                ]
            }
        },
        {
            prod:
            {
                id:"",
                descrip:"Regra de Pino Rustico: 5 x 5 x 9",
                cost:"",
                rust_price:"160",
                cepi_price:"170",
                stock_list:
                [
                    {
                        suc_id:"001",
                        suc_name:"Central",
                        stock:"0"
                    }
                ]
            }
        },
        {
            prod:
            {
                id:"",
                descrip:"Regra de Pino Rustico: 5 x 5 x 10",
                cost:"",
                rust_price:"180",
                cepi_price:"190",
                stock_list:
                [
                    {
                        suc_id:"001",
                        suc_name:"Central",
                        stock:"0"
                    }
                ]
            }
        },
        {
            prod:
            {
                id:"",
                descrip:"Regra de Pino Rustico: 5 x 5 x 12",
                cost:"",
                rust_price:"230",
                cepi_price:"240",
                stock_list:
                [
                    {
                        suc_id:"001",
                        suc_name:"Central",
                        stock:"0"
                    }
                ]
            }
        },
        {
            prod:
            {
                id:"",
                descrip:"Regra de Pino Rustico: 6 x 6 x 7",
                cost:"",
                rust_price:"225",
                cepi_price:"245",
                stock_list:
                [
                    {
                        suc_id:"001",
                        suc_name:"Central",
                        stock:"0"
                    }
                ]
            }
        },
        {
            prod:
            {
                id:"",
                descrip:"Regra de Pino Rustico: 6 x 6 x 8",
                cost:"",
                rust_price:"250",
                cepi_price:"265",
                stock_list:
                [
                    {
                        suc_id:"001",
                        suc_name:"Central",
                        stock:"0"
                    }
                ]
            }
        },
        {
            prod:
            {
                id:"",
                descrip:"Regra de Pino Rustico: 6 x 6 x 9",
                cost:"",
                rust_price:"285",
                cepi_price:"295",
                stock_list:
                [
                    {
                        suc_id:"001",
                        suc_name:"Central",
                        stock:"0"
                    }
                ]
            }
        },
        {
            prod:
            {
                id:"",
                descrip:"Regra de Pino Rustico: 6 x 6 x 10",
                cost:"",
                rust_price:"320",
                cepi_price:"340",
                stock_list:
                [
                    {
                        suc_id:"001",
                        suc_name:"Central",
                        stock:"0"
                    }
                ]
            }
        },
        {
            prod:
            {
                id:"",
                descrip:"Regra de Pino Rustico: 6 x 6 x 12",
                cost:"",
                rust_price:"390",
                cepi_price:"420",
                stock_list:
                [
                    {
                        suc_id:"001",
                        suc_name:"Central",
                        stock:"0"
                    }
                ]
            }
        },
        {
            prod:
            {
                id:"",
                descrip:"Regra de Pino Rustico: 4 x 6 x 7",
                cost:"",
                rust_price:"140",
                cepi_price:"155",
                stock_list:
                [
                    {
                        suc_id:"001",
                        suc_name:"Central",
                        stock:"0"
                    }
                ]
            }
        },
        {
            prod:
            {
                id:"",
                descrip:"Regra de Pino Rustico: 4 x 6 x 8",
                cost:"",
                rust_price:"160",
                cepi_price:"175",
                stock_list:
                [
                    {
                        suc_id:"001",
                        suc_name:"Central",
                        stock:"0"
                    }
                ]
            }
        },
        {
            prod:
            {
                id:"",
                descrip:"Regra de Pino Rustico: 4 x 6 x 9",
                cost:"",
                rust_price:"190",
                cepi_price:"205",
                stock_list:
                [
                    {
                        suc_id:"001",
                        suc_name:"Central",
                        stock:"0"
                    }
                ]
            }
        },
        {
            prod:
            {
                id:"",
                descrip:"Regra de Pino Rustico: 4 x 6 x 10",
                cost:"",
                rust_price:"200",
                cepi_price:"220",
                stock_list:
                [
                    {
                        suc_id:"001",
                        suc_name:"Central",
                        stock:"0"
                    }
                ]
            }
        },
        {
            prod:
            {
                id:"",
                descrip:"Regra de Pino Rustico: 4 x 6 x 12",
                cost:"",
                rust_price:"215",
                cepi_price:"230",
                stock_list:
                [
                    {
                        suc_id:"001",
                        suc_name:"Central",
                        stock:"0"
                    }
                ]
            }
        },
        {
            prod:
            {
                id:"",
                descrip:"Tablon de Pino Rustico: 2 x 4 x 10",
                cost:"",
                rust_price:"55",
                cepi_price:"60",
                stock_list:
                [
                    {
                        suc_id:"001",
                        suc_name:"Central",
                        stock:"0"
                    }
                ]
            }
        },
        {
            prod:
            {
                id:"",
                descrip:"Tablon de Pino Rustico: 2 x 4 x 12",
                cost:"",
                rust_price:"70",
                cepi_price:"75",
                stock_list:
                [
                    {
                        suc_id:"001",
                        suc_name:"Central",
                        stock:"0"
                    }
                ]
            }
        },
        {
            prod:
            {
                id:"",
                descrip:"Tablon de Pino Rustico: 2 x 6 x 7",
                cost:"",
                rust_price:"60",
                cepi_price:"65",
                stock_list:
                [
                    {
                        suc_id:"001",
                        suc_name:"Central",
                        stock:"0"
                    }
                ]
            }
        },
        {
            prod:
            {
                id:"",
                descrip:"Tablon de Pino Rustico: 2 x 6 x 8",
                cost:"",
                rust_price:"70",
                cepi_price:"75",
                stock_list:
                [
                    {
                        suc_id:"001",
                        suc_name:"Central",
                        stock:"0"
                    }
                ]
            }
        },
        {
            prod:
            {
                id:"",
                descrip:"Tablon de Pino Rustico: 2 x 6 x 9",
                cost:"",
                rust_price:"80",
                cepi_price:"85",
                stock_list:
                [
                    {
                        suc_id:"001",
                        suc_name:"Central",
                        stock:"0"
                    }
                ]
            }
        },
        {
            prod:
            {
                id:"",
                descrip:"Tablon de Pino Rustico: 2 x 6 x 10",
                cost:"",
                rust_price:"90",
                cepi_price:"95",
                stock_list:
                [
                    {
                        suc_id:"001",
                        suc_name:"Central",
                        stock:"0"
                    }
                ]
            }
        },
        {
            prod:
            {
                id:"",
                descrip:"Tablon de Pino Rustico: 2 x 6 x 12",
                cost:"",
                rust_price:"105",
                cepi_price:"115",
                stock_list:
                [
                    {
                        suc_id:"001",
                        suc_name:"Central",
                        stock:"0"
                    }
                ]
            }
        },
        {
            prod:
            {
                id:"",
                descrip:"Tabloncillo de Pino Rustico: 1.5 x 12 x 7",
                cost:"",
                rust_price:"95",
                cepi_price:"105",
                stock_list:
                [
                    {
                        suc_id:"001",
                        suc_name:"Central",
                        stock:"0"
                    }
                ]
            }
        },
        {
            prod:
            {
                id:"",
                descrip:"Tabloncillo de Pino Rustico: 1.5 x 12 x 8",
                cost:"",
                rust_price:"70",
                cepi_price:"75",
                stock_list:
                [
                    {
                        suc_id:"001",
                        suc_name:"Central",
                        stock:"0"
                    }
                ]
            }
        },
        {
            prod:
            {
                id:"",
                descrip:"Tabloncillo de Pino Rustico: 1.5 x 12 x 9",
                cost:"",
                rust_price:"80",
                cepi_price:"85",
                stock_list:
                [
                    {
                        suc_id:"001",
                        suc_name:"Central",
                        stock:"0"
                    }
                ]
            }
        },
        {
            prod:
            {
                id:"",
                descrip:"Tabloncillo de Pino Rustico: 1.5 x 12 x 10",
                cost:"",
                rust_price:"135",
                cepi_price:"145",
                stock_list:
                [
                    {
                        suc_id:"001",
                        suc_name:"Central",
                        stock:"0"
                    }
                ]
            }
        },
        {
            prod:
            {
                id:"",
                descrip:"Tabloncillo de Pino Rustico: 1.5 x 12 x 12",
                cost:"",
                rust_price:"175",
                cepi_price:"185",
                stock_list:
                [
                    {
                        suc_id:"001",
                        suc_name:"Central",
                        stock:"0"
                    }
                ]
            }
        },
        {
            prod:
            {
                id:"",
                descrip:"Tablon de Pino Rustico: 2 x 12 x 7",
                cost:"",
                rust_price:"135",
                cepi_price:"145",
                stock_list:
                [
                    {
                        suc_id:"001",
                        suc_name:"Central",
                        stock:"0"
                    }
                ]
            }
        },
        {
            prod:
            {
                id:"",
                descrip:"Tablon de Pino Rustico: 2 x 12 x 8",
                cost:"",
                rust_price:"150",
                cepi_price:"160",
                stock_list:
                [
                    {
                        suc_id:"001",
                        suc_name:"Central",
                        stock:"0"
                    }
                ]
            }
        },
        {
            prod:
            {
                id:"",
                descrip:"Tablon de Pino Rustico: 2 x 12 x 9",
                cost:"",
                rust_price:"170",
                cepi_price:"180",
                stock_list:
                [
                    {
                        suc_id:"001",
                        suc_name:"Central",
                        stock:"0"
                    }
                ]
            }
        },
        {
            prod:
            {
                id:"",
                descrip:"Tablon de Pino Rustico: 2 x 12 x 10",
                cost:"",
                rust_price:"190",
                cepi_price:"200",
                stock_list:
                [
                    {
                        suc_id:"001",
                        suc_name:"Central",
                        stock:"0"
                    }
                ]
            }
        },
        {
            prod:
            {
                id:"",
                descrip:"Tablon de Pino Rustico: 2 x 12 x 12",
                cost:"",
                rust_price:"235",
                cepi_price:"255",
                stock_list:
                [
                    {
                        suc_id:"001",
                        suc_name:"Central",
                        stock:"0"
                    }
                ]
            }
        }

    ];
}
/*

    Pino = 
    [
        {
            ed_id: "1 2 6 Pino",
            nombre: "Duela 1 X 2 X 6 Pino",
            p_rustico:   9,
            p_cepillado: 12,
            existencia:
            [
                {
                    sucursal_id:1,
                    stock:0
                },
                {
                    sucursal_id:2,
                    stock:0
                }

            ]
        },
        {
            ed_id: "1 3 6 Pino",
            nombre: "Duela 1 X 3 X 6 Pino",
            p_rustico:   15,
            p_cepillado: 18,
            existencia:
            [
                {
                    sucursal_id:1,
                    stock:0
                },
                {
                    sucursal_id:2,
                    stock:0
                }

            ]
        },
        {
            ed_id: "1 4 6 Pino",
            nombre: "Duela 1 X 4 X 6 Pino",
            p_rustico:   18,
            p_cepillado: 20,
            existencia:
            [
                {
                    sucursal_id:1,
                    stock:0
                },
                {
                    sucursal_id:2,
                    stock:0
                }

            ]
        },
        {
            ed_id: "1 6 6 Pino",
            nombre: "Duela 1 X 6 X 6 Pino",
            p_rustico:   30,
            p_cepillado: 33,
            existencia:
            [
                {
                    sucursal_id:1,
                    stock:0
                },
                {
                    sucursal_id:2,
                    stock:0
                }

            ]
        },
        {
            ed_id: "1 8 6 Pino",
            nombre: "Tabla 1 X 8 X 6 Pino",
            p_rustico:   35,
            p_cepillado: 40,
            existencia:
            [
                {
                    sucursal_id:1,
                    stock:0
                },
                {
                    sucursal_id:2,
                    stock:0
                }

            ]
        },
        {
            ed_id: "1 10 6 Pino",
            nombre: "Tabla 1 X 10 X 6 Pino",
            p_rustico:   45,
            p_cepillado: 50,
            existencia:
            [
                {
                    sucursal_id:1,
                    stock:0
                },
                {
                    sucursal_id:2,
                    stock:0
                }

            ]
        },
        {
            ed_id: "1 12 6 Pino",
            nombre: "Tabla 1 X 12 X 6 Pino",
            p_rustico:   54,
            p_cepillado: 58,
            existencia:
            [
                {
                    sucursal_id:1,
                    stock:0
                },
                {
                    sucursal_id:2,
                    stock:0
                }

            ]
        },
        {
            ed_id: "2 2 6 Pino",
            nombre: "Regla 2 X 2 X 6 Pino",
            p_rustico:   18,
            p_cepillado: 20,
            existencia:
            [
                {
                    sucursal_id:1,
                    stock:0
                },
                {
                    sucursal_id:2,
                    stock:0
                }

            ]
        },
        {
            ed_id: "2 2 6 Pino",
            nombre: "Regla 2 X 2 X 6 Pino",
            p_rustico:   18,
            p_cepillado: 20,
            existencia:
            [
                {
                    sucursal_id:1,
                    stock:0
                },
                {
                    sucursal_id:2,
                    stock:0
                }

            ]
        },
        {
            ed_id: "2 3 6 Pino",
            nombre: "Regla 2 X 3 X 6 Pino",
            p_rustico:   25,
            p_cepillado: 28,
            existencia:
            [
                {
                    sucursal_id:1,
                    stock:0
                },
                {
                    sucursal_id:2,
                    stock:0
                }

            ]
        },
        {
            ed_id: "3 3 6 Pino",
            nombre: "Regla 3 X 3 X 6 Pino",
            p_rustico:   36,
            p_cepillado: 40,
            existencia:
            [
                {
                    sucursal_id:1,
                    stock:0
                },
                {
                    sucursal_id:2,
                    stock:0
                }

            ]
        },
        {
            ed_id: "3 4 6 Pino",
            nombre: "Regla 3 X 4 X 6 Pino",
            p_rustico:   50,
            p_cepillado: 55,
            existencia:
            [
                {
                    sucursal_id:1,
                    stock:0
                },
                {
                    sucursal_id:2,
                    stock:0
                }

            ]
        },

    ]        
}
*/